package com.hms.backend.doctors.dto;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class DoctorRegistrationResponse {

    private String message;

    private DoctorResponse doctor;

    private String username;

    private String temporaryPassword;

    private Boolean credentialsAutoGenerated;
}