package com.hms.backend.doctors.service;

import com.hms.backend.doctors.dto.*;
import com.hms.backend.doctors.entity.Doctor;
import com.hms.backend.doctors.repository.DoctorRepository;
import com.hms.backend.entity.Role;
import com.hms.backend.entity.User;
import com.hms.backend.entity.UserRole;
import com.hms.backend.repository.RoleRepository;
import com.hms.backend.repository.UserRepository;
import com.hms.backend.repository.UserRoleRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
public class DoctorService {

    private final DoctorRepository doctorRepository;
    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final UserRoleRepository userRoleRepository;
    private final PasswordEncoder passwordEncoder;

    public DoctorRegistrationResponse registerDoctor(
            DoctorRegisterRequest request
    ) {

        Role doctorRole = roleRepository
                .findByRoleCode("DOCTOR")
                .orElseThrow(() ->
                        new RuntimeException("DOCTOR role not found"));

        Doctor doctor = Doctor.builder()
                .fullName(request.getFullName())
                .department(request.getDepartment())
                .phone(request.getPhone())
                .email(request.getEmail())
                .experience(request.getExperience())
                .active(true)
                .build();

        Doctor savedDoctor = doctorRepository.save(doctor);

        savedDoctor.setDoctorCode(
                generateDoctorCode(savedDoctor.getDoctorId())
        );

        boolean usernameAuto =
                request.getUsername() == null ||
                request.getUsername().isBlank();

        boolean passwordAuto =
                request.getPassword() == null ||
                request.getPassword().isBlank();

        String username = usernameAuto
                ? generateUsername(savedDoctor.getDoctorId())
                : request.getUsername();

        String rawPassword = passwordAuto
                ? generatePassword(savedDoctor.getDoctorId())
                : request.getPassword();

        if (userRepository.existsByUsername(username)) {
            throw new RuntimeException(
                    "Username already exists"
            );
        }

        User user = User.builder()
                .fullName(request.getFullName())
                .username(username)
                .email(request.getEmail())
                .phone(request.getPhone())
                .passwordHash(
                        passwordEncoder.encode(rawPassword)
                )
                .active(true)
                .accountLocked(false)
                .build();

        User savedUser = userRepository.save(user);

        UserRole userRole = UserRole.builder()
                .user(savedUser)
                .role(doctorRole)
                .build();

        userRoleRepository.save(userRole);

        savedDoctor.setUser(savedUser);

        Doctor finalDoctor =
                doctorRepository.save(savedDoctor);

        return DoctorRegistrationResponse.builder()
                .message("Doctor registered successfully")
                .doctor(mapToResponse(finalDoctor))
                .username(username)
                .temporaryPassword(rawPassword)
                .credentialsAutoGenerated(
                        usernameAuto || passwordAuto
                )
                .build();
    }

    public List<DoctorResponse> getAllDoctors() {

        return doctorRepository.findAll()
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    public DoctorResponse getDoctorById(Long doctorId) {

        Doctor doctor = doctorRepository
                .findById(doctorId)
                .orElseThrow(() ->
                        new RuntimeException(
                                "Doctor not found"));

        return mapToResponse(doctor);
    }

    public List<DoctorResponse> searchDoctors(
            String keyword
    ) {

        return doctorRepository
                .findByFullNameContainingIgnoreCase(keyword)
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    public DoctorResponse updateDoctor(
            Long doctorId,
            DoctorUpdateRequest request
    ) {

        Doctor doctor = doctorRepository
                .findById(doctorId)
                .orElseThrow(() ->
                        new RuntimeException(
                                "Doctor not found"));

        doctor.setFullName(request.getFullName());
        doctor.setDepartment(request.getDepartment());
        doctor.setPhone(request.getPhone());
        doctor.setEmail(request.getEmail());
        doctor.setExperience(request.getExperience());

        Doctor updatedDoctor =
                doctorRepository.save(doctor);

        return mapToResponse(updatedDoctor);
    }

    private DoctorResponse mapToResponse(
            Doctor doctor
    ) {

        User user = doctor.getUser();

        return DoctorResponse.builder()
                .doctorId(doctor.getDoctorId())
                .doctorCode(doctor.getDoctorCode())
                .userId(
                        user != null
                                ? user.getUserId()
                                : null
                )
                .username(
                        user != null
                                ? user.getUsername()
                                : null
                )
                .fullName(doctor.getFullName())
                .department(doctor.getDepartment())
                .phone(doctor.getPhone())
                .email(doctor.getEmail())
                .experience(doctor.getExperience())
                .active(doctor.getActive())
                .build();
    }

    private String generateDoctorCode(
            Long doctorId
    ) {
        return String.format(
                "DOC-%06d",
                doctorId
        );
    }

    private String generateUsername(
            Long doctorId
    ) {
        return String.format(
                "doc%06d",
                doctorId
        );
    }

    private String generatePassword(
            Long doctorId
    ) {
        return String.format(
                "Doc@%06d",
                doctorId
        );
    }
}