/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceptionistRouteImport } from './routes/receptionist'
import { Route as PharmacistRouteImport } from './routes/pharmacist'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as NurseRouteImport } from './routes/nurse'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceptionistIndexRouteImport } from './routes/receptionist.index'
import { Route as PharmacistIndexRouteImport } from './routes/pharmacist.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as NurseIndexRouteImport } from './routes/nurse.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ReceptionistSearchRouteImport } from './routes/receptionist.search'
import { Route as ReceptionistReportsRouteImport } from './routes/receptionist.reports'
import { Route as ReceptionistRegisterPatientRouteImport } from './routes/receptionist.register-patient'
import { Route as ReceptionistPatientsRouteImport } from './routes/receptionist.patients'
import { Route as ReceptionistDashboardRouteImport } from './routes/receptionist.dashboard'
import { Route as ReceptionistBookAppointmentRouteImport } from './routes/receptionist.book-appointment'
import { Route as ReceptionistBillingRouteImport } from './routes/receptionist.billing'
import { Route as ReceptionistAppointmentsRouteImport } from './routes/receptionist.appointments'
import { Route as PharmacistSalesRouteImport } from './routes/pharmacist.sales'
import { Route as PharmacistPrescriptionsRouteImport } from './routes/pharmacist.prescriptions'
import { Route as PharmacistInventoryRouteImport } from './routes/pharmacist.inventory'
import { Route as PharmacistDashboardRouteImport } from './routes/pharmacist.dashboard'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient.prescriptions'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as PatientBillsRouteImport } from './routes/patient.bills'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as NursePatientsRouteImport } from './routes/nurse.patients'
import { Route as NurseNotesRouteImport } from './routes/nurse.notes'
import { Route as NurseDashboardRouteImport } from './routes/nurse.dashboard'
import { Route as NurseBedsRouteImport } from './routes/nurse.beds'
import { Route as DoctorRecordsRouteImport } from './routes/doctor.records'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorPrescriptionsRouteImport } from './routes/doctor.prescriptions'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorDashboardRouteImport } from './routes/doctor.dashboard'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReceptionistsRouteImport } from './routes/admin.receptionists'
import { Route as AdminPharmacyRouteImport } from './routes/admin.pharmacy'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminBedsRouteImport } from './routes/admin.beds'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'

const ReceptionistRoute = ReceptionistRouteImport.update({
  id: '/receptionist',
  path: '/receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistRoute = PharmacistRouteImport.update({
  id: '/pharmacist',
  path: '/pharmacist',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseRoute = NurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionistIndexRoute = ReceptionistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceptionistRoute,
} as any)
const PharmacistIndexRoute = PharmacistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PharmacistRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const NurseIndexRoute = NurseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NurseRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReceptionistSearchRoute = ReceptionistSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistReportsRoute = ReceptionistReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistRegisterPatientRoute =
  ReceptionistRegisterPatientRouteImport.update({
    id: '/register-patient',
    path: '/register-patient',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const ReceptionistPatientsRoute = ReceptionistPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistDashboardRoute = ReceptionistDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistBookAppointmentRoute =
  ReceptionistBookAppointmentRouteImport.update({
    id: '/book-appointment',
    path: '/book-appointment',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const ReceptionistBillingRoute = ReceptionistBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistAppointmentsRoute =
  ReceptionistAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const PharmacistSalesRoute = PharmacistSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => PharmacistRoute,
} as any)
const PharmacistPrescriptionsRoute = PharmacistPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PharmacistRoute,
} as any)
const PharmacistInventoryRoute = PharmacistInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PharmacistRoute,
} as any)
const PharmacistDashboardRoute = PharmacistDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PharmacistRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBillsRoute = PatientBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const NursePatientsRoute = NursePatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => NurseRoute,
} as any)
const NurseNotesRoute = NurseNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => NurseRoute,
} as any)
const NurseDashboardRoute = NurseDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => NurseRoute,
} as any)
const NurseBedsRoute = NurseBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => NurseRoute,
} as any)
const DoctorRecordsRoute = DoctorRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPrescriptionsRoute = DoctorPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceptionistsRoute = AdminReceptionistsRouteImport.update({
  id: '/receptionists',
  path: '/receptionists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPharmacyRoute = AdminPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBedsRoute = AdminBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/pharmacist': typeof PharmacistRouteWithChildren
  '/receptionist': typeof ReceptionistRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/beds': typeof AdminBedsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/receptionists': typeof AdminReceptionistsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/records': typeof DoctorRecordsRoute
  '/nurse/beds': typeof NurseBedsRoute
  '/nurse/dashboard': typeof NurseDashboardRoute
  '/nurse/notes': typeof NurseNotesRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/bills': typeof PatientBillsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/pharmacist/dashboard': typeof PharmacistDashboardRoute
  '/pharmacist/inventory': typeof PharmacistInventoryRoute
  '/pharmacist/prescriptions': typeof PharmacistPrescriptionsRoute
  '/pharmacist/sales': typeof PharmacistSalesRoute
  '/receptionist/appointments': typeof ReceptionistAppointmentsRoute
  '/receptionist/billing': typeof ReceptionistBillingRoute
  '/receptionist/book-appointment': typeof ReceptionistBookAppointmentRoute
  '/receptionist/dashboard': typeof ReceptionistDashboardRoute
  '/receptionist/patients': typeof ReceptionistPatientsRoute
  '/receptionist/register-patient': typeof ReceptionistRegisterPatientRoute
  '/receptionist/reports': typeof ReceptionistReportsRoute
  '/receptionist/search': typeof ReceptionistSearchRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/pharmacist/': typeof PharmacistIndexRoute
  '/receptionist/': typeof ReceptionistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/beds': typeof AdminBedsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/receptionists': typeof AdminReceptionistsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/records': typeof DoctorRecordsRoute
  '/nurse/beds': typeof NurseBedsRoute
  '/nurse/dashboard': typeof NurseDashboardRoute
  '/nurse/notes': typeof NurseNotesRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/bills': typeof PatientBillsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/pharmacist/dashboard': typeof PharmacistDashboardRoute
  '/pharmacist/inventory': typeof PharmacistInventoryRoute
  '/pharmacist/prescriptions': typeof PharmacistPrescriptionsRoute
  '/pharmacist/sales': typeof PharmacistSalesRoute
  '/receptionist/appointments': typeof ReceptionistAppointmentsRoute
  '/receptionist/billing': typeof ReceptionistBillingRoute
  '/receptionist/book-appointment': typeof ReceptionistBookAppointmentRoute
  '/receptionist/dashboard': typeof ReceptionistDashboardRoute
  '/receptionist/patients': typeof ReceptionistPatientsRoute
  '/receptionist/register-patient': typeof ReceptionistRegisterPatientRoute
  '/receptionist/reports': typeof ReceptionistReportsRoute
  '/receptionist/search': typeof ReceptionistSearchRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/nurse': typeof NurseIndexRoute
  '/patient': typeof PatientIndexRoute
  '/pharmacist': typeof PharmacistIndexRoute
  '/receptionist': typeof ReceptionistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/pharmacist': typeof PharmacistRouteWithChildren
  '/receptionist': typeof ReceptionistRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/beds': typeof AdminBedsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/receptionists': typeof AdminReceptionistsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/records': typeof DoctorRecordsRoute
  '/nurse/beds': typeof NurseBedsRoute
  '/nurse/dashboard': typeof NurseDashboardRoute
  '/nurse/notes': typeof NurseNotesRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/bills': typeof PatientBillsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/pharmacist/dashboard': typeof PharmacistDashboardRoute
  '/pharmacist/inventory': typeof PharmacistInventoryRoute
  '/pharmacist/prescriptions': typeof PharmacistPrescriptionsRoute
  '/pharmacist/sales': typeof PharmacistSalesRoute
  '/receptionist/appointments': typeof ReceptionistAppointmentsRoute
  '/receptionist/billing': typeof ReceptionistBillingRoute
  '/receptionist/book-appointment': typeof ReceptionistBookAppointmentRoute
  '/receptionist/dashboard': typeof ReceptionistDashboardRoute
  '/receptionist/patients': typeof ReceptionistPatientsRoute
  '/receptionist/register-patient': typeof ReceptionistRegisterPatientRoute
  '/receptionist/reports': typeof ReceptionistReportsRoute
  '/receptionist/search': typeof ReceptionistSearchRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/pharmacist/': typeof PharmacistIndexRoute
  '/receptionist/': typeof ReceptionistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/login'
    | '/nurse'
    | '/patient'
    | '/pharmacist'
    | '/receptionist'
    | '/admin/appointments'
    | '/admin/beds'
    | '/admin/billing'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/pharmacy'
    | '/admin/receptionists'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/dashboard'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/records'
    | '/nurse/beds'
    | '/nurse/dashboard'
    | '/nurse/notes'
    | '/nurse/patients'
    | '/patient/appointments'
    | '/patient/bills'
    | '/patient/dashboard'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/pharmacist/dashboard'
    | '/pharmacist/inventory'
    | '/pharmacist/prescriptions'
    | '/pharmacist/sales'
    | '/receptionist/appointments'
    | '/receptionist/billing'
    | '/receptionist/book-appointment'
    | '/receptionist/dashboard'
    | '/receptionist/patients'
    | '/receptionist/register-patient'
    | '/receptionist/reports'
    | '/receptionist/search'
    | '/admin/'
    | '/doctor/'
    | '/nurse/'
    | '/patient/'
    | '/pharmacist/'
    | '/receptionist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/appointments'
    | '/admin/beds'
    | '/admin/billing'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/pharmacy'
    | '/admin/receptionists'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/dashboard'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/records'
    | '/nurse/beds'
    | '/nurse/dashboard'
    | '/nurse/notes'
    | '/nurse/patients'
    | '/patient/appointments'
    | '/patient/bills'
    | '/patient/dashboard'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/pharmacist/dashboard'
    | '/pharmacist/inventory'
    | '/pharmacist/prescriptions'
    | '/pharmacist/sales'
    | '/receptionist/appointments'
    | '/receptionist/billing'
    | '/receptionist/book-appointment'
    | '/receptionist/dashboard'
    | '/receptionist/patients'
    | '/receptionist/register-patient'
    | '/receptionist/reports'
    | '/receptionist/search'
    | '/admin'
    | '/doctor'
    | '/nurse'
    | '/patient'
    | '/pharmacist'
    | '/receptionist'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/login'
    | '/nurse'
    | '/patient'
    | '/pharmacist'
    | '/receptionist'
    | '/admin/appointments'
    | '/admin/beds'
    | '/admin/billing'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/pharmacy'
    | '/admin/receptionists'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/dashboard'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/records'
    | '/nurse/beds'
    | '/nurse/dashboard'
    | '/nurse/notes'
    | '/nurse/patients'
    | '/patient/appointments'
    | '/patient/bills'
    | '/patient/dashboard'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/pharmacist/dashboard'
    | '/pharmacist/inventory'
    | '/pharmacist/prescriptions'
    | '/pharmacist/sales'
    | '/receptionist/appointments'
    | '/receptionist/billing'
    | '/receptionist/book-appointment'
    | '/receptionist/dashboard'
    | '/receptionist/patients'
    | '/receptionist/register-patient'
    | '/receptionist/reports'
    | '/receptionist/search'
    | '/admin/'
    | '/doctor/'
    | '/nurse/'
    | '/patient/'
    | '/pharmacist/'
    | '/receptionist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  LoginRoute: typeof LoginRoute
  NurseRoute: typeof NurseRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  PharmacistRoute: typeof PharmacistRouteWithChildren
  ReceptionistRoute: typeof ReceptionistRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receptionist': {
      id: '/receptionist'
      path: '/receptionist'
      fullPath: '/receptionist'
      preLoaderRoute: typeof ReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist': {
      id: '/pharmacist'
      path: '/pharmacist'
      fullPath: '/pharmacist'
      preLoaderRoute: typeof PharmacistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse': {
      id: '/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receptionist/': {
      id: '/receptionist/'
      path: '/'
      fullPath: '/receptionist/'
      preLoaderRoute: typeof ReceptionistIndexRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/pharmacist/': {
      id: '/pharmacist/'
      path: '/'
      fullPath: '/pharmacist/'
      preLoaderRoute: typeof PharmacistIndexRouteImport
      parentRoute: typeof PharmacistRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/nurse/': {
      id: '/nurse/'
      path: '/'
      fullPath: '/nurse/'
      preLoaderRoute: typeof NurseIndexRouteImport
      parentRoute: typeof NurseRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/receptionist/search': {
      id: '/receptionist/search'
      path: '/search'
      fullPath: '/receptionist/search'
      preLoaderRoute: typeof ReceptionistSearchRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/reports': {
      id: '/receptionist/reports'
      path: '/reports'
      fullPath: '/receptionist/reports'
      preLoaderRoute: typeof ReceptionistReportsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/register-patient': {
      id: '/receptionist/register-patient'
      path: '/register-patient'
      fullPath: '/receptionist/register-patient'
      preLoaderRoute: typeof ReceptionistRegisterPatientRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/patients': {
      id: '/receptionist/patients'
      path: '/patients'
      fullPath: '/receptionist/patients'
      preLoaderRoute: typeof ReceptionistPatientsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/dashboard': {
      id: '/receptionist/dashboard'
      path: '/dashboard'
      fullPath: '/receptionist/dashboard'
      preLoaderRoute: typeof ReceptionistDashboardRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/book-appointment': {
      id: '/receptionist/book-appointment'
      path: '/book-appointment'
      fullPath: '/receptionist/book-appointment'
      preLoaderRoute: typeof ReceptionistBookAppointmentRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/billing': {
      id: '/receptionist/billing'
      path: '/billing'
      fullPath: '/receptionist/billing'
      preLoaderRoute: typeof ReceptionistBillingRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/appointments': {
      id: '/receptionist/appointments'
      path: '/appointments'
      fullPath: '/receptionist/appointments'
      preLoaderRoute: typeof ReceptionistAppointmentsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/pharmacist/sales': {
      id: '/pharmacist/sales'
      path: '/sales'
      fullPath: '/pharmacist/sales'
      preLoaderRoute: typeof PharmacistSalesRouteImport
      parentRoute: typeof PharmacistRoute
    }
    '/pharmacist/prescriptions': {
      id: '/pharmacist/prescriptions'
      path: '/prescriptions'
      fullPath: '/pharmacist/prescriptions'
      preLoaderRoute: typeof PharmacistPrescriptionsRouteImport
      parentRoute: typeof PharmacistRoute
    }
    '/pharmacist/inventory': {
      id: '/pharmacist/inventory'
      path: '/inventory'
      fullPath: '/pharmacist/inventory'
      preLoaderRoute: typeof PharmacistInventoryRouteImport
      parentRoute: typeof PharmacistRoute
    }
    '/pharmacist/dashboard': {
      id: '/pharmacist/dashboard'
      path: '/dashboard'
      fullPath: '/pharmacist/dashboard'
      preLoaderRoute: typeof PharmacistDashboardRouteImport
      parentRoute: typeof PharmacistRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/bills': {
      id: '/patient/bills'
      path: '/bills'
      fullPath: '/patient/bills'
      preLoaderRoute: typeof PatientBillsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/nurse/patients': {
      id: '/nurse/patients'
      path: '/patients'
      fullPath: '/nurse/patients'
      preLoaderRoute: typeof NursePatientsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/notes': {
      id: '/nurse/notes'
      path: '/notes'
      fullPath: '/nurse/notes'
      preLoaderRoute: typeof NurseNotesRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/dashboard': {
      id: '/nurse/dashboard'
      path: '/dashboard'
      fullPath: '/nurse/dashboard'
      preLoaderRoute: typeof NurseDashboardRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/beds': {
      id: '/nurse/beds'
      path: '/beds'
      fullPath: '/nurse/beds'
      preLoaderRoute: typeof NurseBedsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/doctor/records': {
      id: '/doctor/records'
      path: '/records'
      fullPath: '/doctor/records'
      preLoaderRoute: typeof DoctorRecordsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receptionists': {
      id: '/admin/receptionists'
      path: '/receptionists'
      fullPath: '/admin/receptionists'
      preLoaderRoute: typeof AdminReceptionistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pharmacy': {
      id: '/admin/pharmacy'
      path: '/pharmacy'
      fullPath: '/admin/pharmacy'
      preLoaderRoute: typeof AdminPharmacyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/beds': {
      id: '/admin/beds'
      path: '/beds'
      fullPath: '/admin/beds'
      preLoaderRoute: typeof AdminBedsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminBedsRoute: typeof AdminBedsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminPharmacyRoute: typeof AdminPharmacyRoute
  AdminReceptionistsRoute: typeof AdminReceptionistsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminBedsRoute: AdminBedsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminPharmacyRoute: AdminPharmacyRoute,
  AdminReceptionistsRoute: AdminReceptionistsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorPrescriptionsRoute: typeof DoctorPrescriptionsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorRecordsRoute: typeof DoctorRecordsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorPrescriptionsRoute: DoctorPrescriptionsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorRecordsRoute: DoctorRecordsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface NurseRouteChildren {
  NurseBedsRoute: typeof NurseBedsRoute
  NurseDashboardRoute: typeof NurseDashboardRoute
  NurseNotesRoute: typeof NurseNotesRoute
  NursePatientsRoute: typeof NursePatientsRoute
  NurseIndexRoute: typeof NurseIndexRoute
}

const NurseRouteChildren: NurseRouteChildren = {
  NurseBedsRoute: NurseBedsRoute,
  NurseDashboardRoute: NurseDashboardRoute,
  NurseNotesRoute: NurseNotesRoute,
  NursePatientsRoute: NursePatientsRoute,
  NurseIndexRoute: NurseIndexRoute,
}

const NurseRouteWithChildren = NurseRoute._addFileChildren(NurseRouteChildren)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientBillsRoute: typeof PatientBillsRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientBillsRoute: PatientBillsRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface PharmacistRouteChildren {
  PharmacistDashboardRoute: typeof PharmacistDashboardRoute
  PharmacistInventoryRoute: typeof PharmacistInventoryRoute
  PharmacistPrescriptionsRoute: typeof PharmacistPrescriptionsRoute
  PharmacistSalesRoute: typeof PharmacistSalesRoute
  PharmacistIndexRoute: typeof PharmacistIndexRoute
}

const PharmacistRouteChildren: PharmacistRouteChildren = {
  PharmacistDashboardRoute: PharmacistDashboardRoute,
  PharmacistInventoryRoute: PharmacistInventoryRoute,
  PharmacistPrescriptionsRoute: PharmacistPrescriptionsRoute,
  PharmacistSalesRoute: PharmacistSalesRoute,
  PharmacistIndexRoute: PharmacistIndexRoute,
}

const PharmacistRouteWithChildren = PharmacistRoute._addFileChildren(
  PharmacistRouteChildren,
)

interface ReceptionistRouteChildren {
  ReceptionistAppointmentsRoute: typeof ReceptionistAppointmentsRoute
  ReceptionistBillingRoute: typeof ReceptionistBillingRoute
  ReceptionistBookAppointmentRoute: typeof ReceptionistBookAppointmentRoute
  ReceptionistDashboardRoute: typeof ReceptionistDashboardRoute
  ReceptionistPatientsRoute: typeof ReceptionistPatientsRoute
  ReceptionistRegisterPatientRoute: typeof ReceptionistRegisterPatientRoute
  ReceptionistReportsRoute: typeof ReceptionistReportsRoute
  ReceptionistSearchRoute: typeof ReceptionistSearchRoute
  ReceptionistIndexRoute: typeof ReceptionistIndexRoute
}

const ReceptionistRouteChildren: ReceptionistRouteChildren = {
  ReceptionistAppointmentsRoute: ReceptionistAppointmentsRoute,
  ReceptionistBillingRoute: ReceptionistBillingRoute,
  ReceptionistBookAppointmentRoute: ReceptionistBookAppointmentRoute,
  ReceptionistDashboardRoute: ReceptionistDashboardRoute,
  ReceptionistPatientsRoute: ReceptionistPatientsRoute,
  ReceptionistRegisterPatientRoute: ReceptionistRegisterPatientRoute,
  ReceptionistReportsRoute: ReceptionistReportsRoute,
  ReceptionistSearchRoute: ReceptionistSearchRoute,
  ReceptionistIndexRoute: ReceptionistIndexRoute,
}

const ReceptionistRouteWithChildren = ReceptionistRoute._addFileChildren(
  ReceptionistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  LoginRoute: LoginRoute,
  NurseRoute: NurseRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  PharmacistRoute: PharmacistRouteWithChildren,
  ReceptionistRoute: ReceptionistRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
