package com.hms.backend.patients.service;

import com.hms.backend.patients.dto.PatientRegisterRequest;
import com.hms.backend.patients.dto.PatientRegistrationResponse;
import com.hms.backend.patients.dto.PatientResponse;
import com.hms.backend.patients.dto.PatientStatusRequest;
import com.hms.backend.patients.dto.PatientUpdateRequest;
import com.hms.backend.patients.entity.Patient;
import com.hms.backend.patients.repository.PatientRepository;
import com.hms.backend.entity.Role;
import com.hms.backend.entity.User;
import com.hms.backend.entity.UserRole;
import com.hms.backend.repository.RoleRepository;
import com.hms.backend.repository.UserRepository;
import com.hms.backend.repository.UserRoleRepository;
import com.hms.backend.patients.entity.InsuranceProvider;
import com.hms.backend.patients.entity.PatientAllergy;
import com.hms.backend.patients.repository.InsuranceProviderRepository;
import com.hms.backend.patients.dto.PatientResponse.AllergyDto;
import com.hms.backend.patients.dto.PatientAllergyRequest;
import com.hms.backend.entity.MedicalConcept;
import com.hms.backend.repository.MedicalConceptRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@RequiredArgsConstructor
public class PatientService {

    private final PatientRepository patientRepository;
    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final UserRoleRepository userRoleRepository;
    private final PasswordEncoder passwordEncoder;
    private final InsuranceProviderRepository insuranceProviderRepository;
    private final MedicalConceptRepository medicalConceptRepository;

    @Transactional
    public PatientRegistrationResponse registerPatient(PatientRegisterRequest request) {

        Role patientRole = roleRepository.findByRoleCode("PATIENT")
                .orElseThrow(() -> new RuntimeException("PATIENT role not found"));

        Patient patient = Patient.builder()
                .fullName(request.getFullName())
                .dateOfBirth(request.getDateOfBirth())
                .gender(request.getGender())
                .bloodGroup(request.getBloodGroup())
                .phone(normalize(request.getPhone()))
                .email(normalize(request.getEmail()))
                .address(request.getAddress())
                .emergencyContactName(request.getEmergencyContactName())
                .emergencyContactPhone(normalize(request.getEmergencyContactPhone()))
                .active(true)
                .build();

        if (request.getInsuranceProviderId() != null) {
            InsuranceProvider provider = insuranceProviderRepository.findById(request.getInsuranceProviderId())
                    .orElseThrow(() -> new RuntimeException("Insurance Provider not found"));
            patient.setInsuranceProvider(provider);
            patient.setPolicyNumber(request.getPolicyNumber());
        }

        Patient savedPatient = patientRepository.save(patient);

        String patientCode = generatePatientCode(savedPatient.getPatientId());
        savedPatient.setPatientCode(patientCode);

        boolean usernameAutoGenerated = isBlank(request.getUsername());
        boolean passwordAutoGenerated = isBlank(request.getPassword());

        String username = usernameAutoGenerated
                ? generateUsername(savedPatient.getPatientId())
                : request.getUsername().trim();

        String rawPassword = passwordAutoGenerated
                ? generatePassword(savedPatient.getPatientId())
                : request.getPassword();

        if (userRepository.existsByUsername(username)) {
            throw new RuntimeException("Username already exists");
        }

        String email = normalize(request.getEmail());

        if (email != null && userRepository.existsByEmail(email)) {
            throw new RuntimeException("Email already exists in login users");
        }

        User user = User.builder()
                .username(username)
                .passwordHash(passwordEncoder.encode(rawPassword))
                .fullName(request.getFullName())
                .email(email)
                .phone(normalize(request.getPhone()))
                .active(true)
                .accountLocked(false)
                .build();

        User savedUser = userRepository.save(user);

        UserRole userRole = UserRole.builder()
                .user(savedUser)
                .role(patientRole)
                .build();

        userRoleRepository.save(userRole);

        savedPatient.setUser(savedUser);

        Patient finalPatient = patientRepository.save(savedPatient);

        return PatientRegistrationResponse.builder()
                .message("Patient registered successfully")
                .patient(mapToResponse(finalPatient))
                .username(username)
                .temporaryPassword(rawPassword)
                .credentialsAutoGenerated(usernameAutoGenerated || passwordAutoGenerated)
                .build();
    }

    @Transactional(readOnly = true)
    public List<PatientResponse> getAllPatients() {
        return patientRepository.findAll()
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    @Transactional(readOnly = true)
    public PatientResponse getPatientById(Long patientId) {
        Patient patient = patientRepository.findById(patientId)
                .orElseThrow(() -> new RuntimeException("Patient not found"));

        return mapToResponse(patient);
    }

    @Transactional(readOnly = true)
    public PatientResponse getPatientByUserId(Long userId) {
        Patient patient = patientRepository.findByUserUserId(userId)
                .orElseThrow(() -> new RuntimeException("Patient not found for userId: " + userId));
        return mapToResponse(patient);
    }

    @Transactional(readOnly = true)
    public List<PatientResponse> searchPatients(String keyword) {

        if (isBlank(keyword)) {
            return getAllPatients();
        }

        return patientRepository
                .findByFullNameContainingIgnoreCaseOrPhoneContainingOrPatientCodeContainingIgnoreCase(
                        keyword,
                        keyword,
                        keyword
                )
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    @Transactional
    public PatientResponse updatePatient(Long patientId, PatientUpdateRequest request) {

        Patient patient = patientRepository.findById(patientId)
                .orElseThrow(() -> new RuntimeException("Patient not found"));

        patient.setFullName(request.getFullName());
        patient.setDateOfBirth(request.getDateOfBirth());
        patient.setGender(request.getGender());
        patient.setBloodGroup(request.getBloodGroup());
        patient.setPhone(normalize(request.getPhone()));
        patient.setEmail(normalize(request.getEmail()));
        patient.setAddress(request.getAddress());
        patient.setEmergencyContactName(request.getEmergencyContactName());
        patient.setEmergencyContactPhone(normalize(request.getEmergencyContactPhone()));

        if (request.getInsuranceProviderId() != null) {
            InsuranceProvider provider = insuranceProviderRepository.findById(request.getInsuranceProviderId())
                    .orElseThrow(() -> new RuntimeException("Insurance Provider not found"));
            patient.setInsuranceProvider(provider);
            patient.setPolicyNumber(request.getPolicyNumber());
        } else {
            patient.setInsuranceProvider(null);
            patient.setPolicyNumber(null);
        }

        Patient savedPatient = patientRepository.save(patient);

        return mapToResponse(savedPatient);
    }

    @Transactional
    public PatientResponse updatePatientStatus(Long patientId, PatientStatusRequest request) {

        Patient patient = patientRepository.findById(patientId)
                .orElseThrow(() -> new RuntimeException("Patient not found"));

        patient.setActive(request.getActive());

        if (patient.getUser() != null) {
            patient.getUser().setActive(request.getActive());
        }

        Patient savedPatient = patientRepository.save(patient);

        return mapToResponse(savedPatient);
    }

    @Transactional
    public PatientResponse addAllergyToPatient(Long patientId, PatientAllergyRequest request) {
        Patient patient = patientRepository.findById(patientId)
                .orElseThrow(() -> new RuntimeException("Patient not found"));
        // check if already exists
        boolean exists = patient.getAllergies() != null && patient.getAllergies().stream()
                .anyMatch(a -> a.getAllergyName().equalsIgnoreCase(request.getAllergyName()));
        if (exists) {
            throw new RuntimeException("Patient already has this allergy documented.");
        }

        PatientAllergy allergy = PatientAllergy.builder()
                .patient(patient)
                .allergyName(request.getAllergyName())
                .severity(request.getSeverity())
                .notes(request.getNotes())
                .recordedAt(java.time.LocalDateTime.now())
                .build();

        patient.addAllergy(allergy);
        Patient saved = patientRepository.save(patient);
        return mapToResponse(saved);
    }

    @Transactional
    public PatientRegistrationResponse resetCredentials(Long patientId) {
        Patient patient = patientRepository.findById(patientId)
                .orElseThrow(() -> new RuntimeException("Patient not found"));

        User user = patient.getUser();
        if (user == null) {
            throw new RuntimeException("Patient does not have a user account");
        }

        String newPassword = generatePassword(patient.getPatientId());
        user.setPasswordHash(passwordEncoder.encode(newPassword));
        userRepository.save(user);

        return PatientRegistrationResponse.builder()
                .message("Credentials reset successfully")
                .patient(mapToResponse(patient))
                .username(user.getUsername())
                .temporaryPassword(newPassword)
                .credentialsAutoGenerated(true)
                .build();
    }

    private String generatePatientCode(Long patientId) {
        return String.format("PAT-%06d", patientId);
    }

    private String generateUsername(Long patientId) {
        String baseUsername = String.format("pat%06d", patientId);
        String username = baseUsername;
        int count = 1;

        while (userRepository.existsByUsername(username)) {
            username = baseUsername + count;
            count++;
        }

        return username;
    }

    private String generatePassword(Long patientId) {
        return String.format("Pat@%06d", patientId);
    }

    private PatientResponse mapToResponse(Patient patient) {

        User user = patient.getUser();

        return PatientResponse.builder()
                .patientId(patient.getPatientId())
                .patientCode(patient.getPatientCode())
                .userId(user != null ? user.getUserId() : null)
                .username(user != null ? user.getUsername() : null)
                .fullName(patient.getFullName())
                .dateOfBirth(patient.getDateOfBirth())
                .gender(patient.getGender())
                .bloodGroup(patient.getBloodGroup())
                .phone(patient.getPhone())
                .email(patient.getEmail())
                .address(patient.getAddress())
                .emergencyContactName(patient.getEmergencyContactName())
                .emergencyContactPhone(patient.getEmergencyContactPhone())
                .insuranceProviderId(patient.getInsuranceProvider() != null ? patient.getInsuranceProvider().getId() : null)
                .insuranceProviderName(patient.getInsuranceProvider() != null ? patient.getInsuranceProvider().getProviderName() : null)
                .policyNumber(patient.getPolicyNumber())
                .allergies(patient.getAllergies() != null ? patient.getAllergies().stream().map(a -> AllergyDto.builder()
                        .id(a.getId())
                        .allergyName(a.getAllergyName())
                        .severity(a.getSeverity())
                        .notes(a.getNotes())
                        .build()).toList() : new java.util.ArrayList<>())
                .active(patient.getActive())
                .build();
    }

    private String normalize(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        return value.trim();
    }

    private boolean isBlank(String value) {
        return value == null || value.isBlank();
    }
}