spring.application.name=backend
server.port=${PORT:8081}

# MySQL Database Config (Railway Public Connection)
spring.datasource.url=jdbc:mysql://sakura.proxy.rlwy.net:59387/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MeBeVPoYSZNVRBKwXOgPbVeOtErSiSma
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection Pooling (Increase timeout over internet)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Force the MySQL Dialect so Hibernate doesn't crash trying to guess it over the proxy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect