export type Role =
  | "ADMIN"
  | "DOCTOR"
  | "RECEPTIONIST"
  | "PATIENT"
  | "NURSE"
  | "PHARMACIST";

export interface AuthUser {
  success?: boolean;
  message?: string;
  userId?: number | string;
  username?: string;
  fullName?: string;
  role?: Role | string;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface AppUser {
  id?: number | string;
  username?: string;
  fullName?: string;
  email?: string;
  phone?: string;
  role?: string;
  roleCode?: string;
  roleName?: string;
  active?: boolean;
  accountLocked?: boolean;
  [key: string]: unknown;
}

export interface RoleItem {
  id?: number | string;
  roleCode?: string;
  code?: string;
  roleName?: string;
  name?: string;
  [key: string]: unknown;
}

export interface CreateUserRequest {
  username: string;
  password: string;
  fullName: string;
  email: string;
  phone: string;
  roleCode: string;
}

export interface UpdateUserRequest {
  fullName: string;
  email: string;
  phone: string;
}

export interface Patient {
  id?: number | string;
  username?: string;
  fullName?: string;
  dateOfBirth?: string;
  gender?: string;
  bloodGroup?: string;
  phone?: string;
  email?: string;
  address?: string;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  active?: boolean;
  [key: string]: unknown;
}

export interface PatientRequest {
  username?: string;
  password?: string;
  fullName: string;
  dateOfBirth: string;
  gender: string;
  bloodGroup: string;
  phone: string;
  email: string;
  address: string;
  emergencyContactName: string;
  emergencyContactPhone: string;
}

export interface Doctor {
  id?: number | string;
  doctorId?: number | string;
  userId?: number | string;
  username?: string;
  fullName?: string;
  department?: string;
  doctorCode?: string;
  phone?: string;
  email?: string;
  experience?: number;
  active?: boolean;
  [key: string]: unknown;
}

export interface DoctorRequest {
  username?: string;
  password?: string;
  fullName: string;
  department: string;
  phone: string;
  email: string;
  experience: number;
}

export interface Appointment {
  id?: number | string;
  appointmentId?: number | string;
  appointmentNumber?: string;
  tokenNumber?: string;
  appointmentDate?: string;
  appointmentTime?: string;
  reasonForVisit?: string;
  status?: string;
  patientId?: number | string;
  patientName?: string;
  doctorId?: number | string;
  doctorName?: string;
  [key: string]: unknown;
}

export interface AppointmentRequest {
  patientId: string | number;
  doctorId: string | number;
  appointmentDate: string;
  appointmentTime: string;
  reasonForVisit: string;
}

export interface DoctorCreateResponse {
  credentialsAutoGenerated?: boolean;
  doctor?: Doctor;
  message?: string;
  temporaryPassword?: string;
  username?: string;
}

export interface DashboardSummary {
  [key: string]: unknown;
}
